#!/usr/bin/env node
// Regenerates the "Available Categories" table and the agent/category counts
// in skills/template-catalog/SKILL.md from the UPSTREAM SOURCE OF TRUTH:
// the davila7/claude-code-templates directory tree `cli-tool/components/agents`
// — the same tree `npx claude-code-templates --agent <cat>/<name>` installs from.
//
// NOT docs/api/agents.json — that index is incomplete (156 vs 421 real) and
// must never be used here.
//
// Usage:   node scripts/sync-catalog.mjs
//   Set GITHUB_TOKEN to raise the GitHub API rate limit (60/h anon → 5000/h).
//
// Failure is LOUD: if the upstream path is gone or zero agents are found,
// the script exits non-zero and leaves SKILL.md untouched. It does not write
// a silently-wrong table.

import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const OWNER = 'davila7';
const REPO = 'claude-code-templates';
const REF = 'main';
const COMPONENTS_PATH = 'cli-tool/components';
const SKILL = join(dirname(fileURLToPath(import.meta.url)), '..', 'skills', 'template-catalog', 'SKILL.md');
const START = '<!-- catalog:start (auto-generated by scripts/sync-catalog.mjs — do not edit by hand) -->';
const END = '<!-- catalog:end -->';

const headers = {
  'User-Agent': 'template-bridge-sync-catalog',
  Accept: 'application/vnd.github+json',
  ...(process.env.GITHUB_TOKEN ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {}),
};

// Uses curl (read-only) rather than node fetch: portable, and the only
// network path available in sandboxed environments here.
function gh(url) {
  const args = ['-fsSL'];
  for (const [k, v] of Object.entries(headers)) args.push('-H', `${k}: ${v}`);
  args.push(url);
  let out;
  try {
    out = execFileSync('curl', args, { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 });
  } catch (e) {
    throw new Error(`curl failed for ${url}: ${e.message}`);
  }
  return JSON.parse(out);
}

// 1. Resolve the `agents` tree SHA dynamically from the live ref (robust to
//    content changes; breaks loudly only if the path itself is restructured).
const components = await gh(
  `https://api.github.com/repos/${OWNER}/${REPO}/contents/${COMPONENTS_PATH}?ref=${REF}`,
);
const agentsDir = components.find((e) => e.name === 'agents' && e.type === 'dir');
if (!agentsDir) {
  throw new Error(
    `Upstream layout changed: '${COMPONENTS_PATH}/agents' not found. ` +
      `Fix the path in scripts/sync-catalog.mjs and re-run.`,
  );
}

// 2. One recursive tree call → every blob under agents/.
const tree = await gh(
  `https://api.github.com/repos/${OWNER}/${REPO}/git/trees/${agentsDir.sha}?recursive=1`,
);
if (tree.truncated) throw new Error('Tree response truncated — counts would be partial. Aborting.');

// 3. An installable agent is exactly `<category>/<name>.md` (one level deep).
const AGENT_RE = /^([^/]+)\/([^/]+)\.md$/;
const byCat = new Map();
for (const node of tree.tree) {
  if (node.type !== 'blob') continue;
  const m = AGENT_RE.exec(node.path);
  if (!m) continue;
  const [, cat, name] = m;
  if (!byCat.has(cat)) byCat.set(cat, []);
  byCat.get(cat).push(name);
}

const cats = [...byCat.keys()].sort();
const total = [...byCat.values()].reduce((s, a) => s + a.length, 0);
if (total === 0) throw new Error('Zero agents parsed — refusing to write an empty catalog.');

// 4. Build the table. "Sample Agents" = first 3 by case-insensitive name sort
//    (deterministic & reproducible — not a subjective "top").
const rows = cats.map((cat) => {
  const names = byCat.get(cat).sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
  return `| ${cat} | ${names.length} | ${names.slice(0, 3).join(', ')} |`;
});
const table = [
  START,
  '',
  `_${total} agents across ${cats.length} categories. Auto-generated from the upstream`,
  '`cli-tool/components/agents` tree — run `node scripts/sync-catalog.mjs` to refresh._',
  '',
  '| Category | Count | Sample Agents |',
  '|----------|-------|---------------|',
  ...rows,
  '',
  END,
].join('\n');

// 5. Patch SKILL.md: table block + the two count strings.
let md = readFileSync(SKILL, 'utf8');
const blockRe = new RegExp(`${escapeRe(START)}[\\s\\S]*?${escapeRe(END)}`);
if (!blockRe.test(md)) throw new Error(`Markers not found in ${SKILL}. Add ${START} … ${END}.`);
md = md.replace(blockRe, table);
md = md.replace(/\(\s*[\d,+]+\s*agents,\s*\d+\s*categories\)/, `(${total} agents, ${cats.length} categories)`);
md = md.replace(/^# Template Catalog — .*$/m, `# Template Catalog — ${total} Specialist Agents`);
writeFileSync(SKILL, md);

console.log(`sync-catalog: ${total} agents, ${cats.length} categories → ${SKILL}`);

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
